language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
 - echo "nothing to be installed yet"

# Scripts to be run as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-node .
  - docker tag simple-node ikenjoku/simple-node:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ikenjoku/simple-node
